name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Java 버전 설정 (필요에 따라 변경)

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via SSH
        run: |
          rsync -avz --exclude '.git/' -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.USER }}@${{ secrets.HOST }}:/home/leesh/Sparta/WeatherWear

      - name: Create environment variables file
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" > env-vars.env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> env-vars.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> env-vars.env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> env-vars.env
          echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> env-vars.env
          echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> env-vars.env
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> env-vars.env
          echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> env-vars.env
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> env-vars.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> env-vars.env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> env-vars.env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> env-vars.env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> env-vars.env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> env-vars.env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> env-vars.env
          echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> env-vars.env
          echo "AWS_S3_REGION=${{ secrets.AWS_S3_REGION }}" >> env-vars.env
          echo "LOCAL_DB_USERNAME=${{ secrets.LOCAL_DB_USERNAME }}" >> env-vars.env
          echo "LOCAL_DB_PASSWORD=${{ secrets.LOCAL_DB_PASSWORD }}" >> env-vars.env

      - name: Upload environment variables file to server
        run: |
          scp -o StrictHostKeyChecking=no env-vars.env ${{ secrets.USER }}@${{ secrets.HOST }}:/home/leesh/Sparta/WeatherWear

      - name: Clean up
        run: |
          rm -f env-vars.env

      - name: Build and start Spring application on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          cd /home/leesh/Sparta/WeatherWear
          
          # Stop existing application if running
          pkill -f './gradlew bootRun' || true

          # Build the application on the server
          ./gradlew build

          # Start the new application
          nohup ./gradlew bootRun > bootRun.log 2>&1 &
          EOF
